# Generated by Django 5.2.5 on 2025-08-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_options_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='teacher',
        ),
    ]
