# Generated by Django 5.2.5 on 2025-08-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_chapter_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course',
            new_name='course-chapters',
        ),
    ]
