# Generated by Django 5.2.5 on 2025-08-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_course_chapter_course_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course-chapters',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='main.course'),
        ),
    ]
