# Generated by Django 5.2.5 on 2025-08-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_category_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
