# Generated by Django 5.2.5 on 2025-08-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Skills',
            new_name='skills',
        ),
    ]
