# Generated by Django 5.2.5 on 2025-08-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='user_name',
        ),
    ]
