# Generated by Django 5.2.5 on 2025-08-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_username_student_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
