# Generated by Django 5.2.5 on 2025-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profile_imgs/'),
        ),
    ]
