# Generated by Django 5.2.5 on 2025-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_teacher_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
