# Generated by Django 5.2.5 on 2025-09-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
