# Generated by Django 5.2.5 on 2025-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_studentassignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
