# Generated by Django 5.2.5 on 2025-09-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField()),
                ('notification_for', models.CharField(max_length=120)),
                ('notification_created_time', models.DateTimeField(auto_now_add=True)),
                ('notification_read_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '10. Notification',
            },
        ),
    ]
