# Generated by Django 5.2.5 on 2025-09-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_read_status',
            field=models.BooleanField(default=False, verbose_name='Notification status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_text',
            field=models.TextField(verbose_name='Notification Text'),
        ),
    ]
