# Generated by Django 5.2.5 on 2025-09-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_notification_notification_read_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_text',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Notification subject'),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_for',
            field=models.CharField(max_length=200, verbose_name='Notification for'),
        ),
    ]
